 export const AllProjects = [
    { id:"5",
      title: "one nnnnnnn",
      subtitle: " subtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitle",
      category: ["css", "node"],
      imgpath: "./LOG1.jpeg",
    },
    {
      id:"4",
      title: "one nnnnnnn",
      subtitle: " subtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitle",
      category: ["angular"],
      imgpath: "./images/download.jpeg",
    },
    {
      id:"3",
      title: "one nnnnnnn",
      subtitle: " subtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitlesubtitle",
      category: ["react", "node"],
      imgpath: "dg",
    },
    {id:"2",
      title: "DOTS Coffe",
      subtitle: "Join our community of coffee lovers and stay updated on the latest trends, recipes, and coffee culture. At [DOTS Coffee ], we believe that coffee is more than a beverage; it's a lifestyle, a journey, and a daily celebration of the extraordinary flavors that make each cup unique.",
      category: ["js","css"],
      imgpath: "./images/dots.jpeg",
      videoPath:"./videos/dots.mp4",
      web:"https://esraafathi.github.io/Coffe-web/",
      git:"https://github.com/EsraaFathi/Coffe-web.git",
    },
    {
      id:"1",
      title: "CRUD SYSTEM",
      subtitle: "    A CRUD system is a software framework or approach that facilitates the management of data in a database. CRUD  stands for Create, Read, Update, and Delete, which represent the basic operations that can be performed on data using  javascript",
      category: ["",'css'],
      git:"https://github.com/EsraaFathi/Crud-System.git",
      web:"https://esraafathi.github.io/CRUD-/",
      imgpath: "./images/crud_REC.png",
      videoPath:"./videos/cruds.mp4",
    },
  ];